package ru.cw.launcher.engine

import java.util.Locale

/** Тексты лаунчера. Пустой язык — язык телефона, не Windows. */
object Lang {
    @Volatile private var code = "ru"
    private val all = HashMap<String, Map<String, String>>()

    init {
        put("ru", mapOf(
            "news" to "Новости", "latest" to "Последние обновления", "more" to "Подробнее →",
            "settings" to "Настройки", "version" to "Выбор версии", "support" to "Тех. Поддержка",
            "folder" to "Папка\nMinecraft", "mods" to "Моды", "skin" to "Скин", "logs" to "Логи",
            "close" to "Закрыть", "close_game" to "Закрыть", "cancel" to "Отмена",
            "launch" to "Запустить", "install" to "Установить", "update_btn" to "Обновить",
            "check" to "Проверить сборку", "retry" to "Повторить", "checking" to "Проверка…", "starting" to "Запускается",
            "running" to "Запущен", "go" to "Запуск", "ready" to "Готово к запуску",
            "offline_go" to "Запуск без интернета", "java_missing" to "Java для запуска не найдена",
            "status_build" to "Состояние сборки", "status_err" to "Проблемы сборки",
            "status_work" to "Процесс установки", "status_info" to "Информация",
            "mods_fresh" to "Моды: актуальны", "mods_check" to "Моды: проверить",
            "foot_none" to "Сервер: нет данных", "repeat" to "Повторить",
            "news_down" to "Новости недоступны", "news_empty" to "Источник не ответил.",
            "updates_title" to "Обновления Common World", "updates_empty" to "Список обновлений пуст",
            "updates_hint" to "Нажмите «Повторить», чтобы запросить список ещё раз.",
            "saved" to "Настройки сохранены",
            "tab_main" to "Основные", "tab_game" to "Игра", "tab_mods" to "Моды",
            "tab_look" to "Внешний вид", "tab_extra" to "Дополнительно",
            "save" to "Сохранить изменения", "reset" to "Сбросить настройки",
            "lang" to "Язык интерфейса",
            "lang_hint" to "Язык лаунчера и Minecraft. После сохранения лаунчер переключается сразу.",
            "lang_pick" to "Выберите язык", "lang_sys" to "Как в системе",
            "ram" to "Оперативная память",
            "ram_hint" to "Ползунок идёт до всей памяти телефона.",
            "ram_of" to "из", "gb" to "ГБ",
            "java" to "Java", "java_h" to "Своя Java вместо встроенной. Нужна Java 17.",
            "jvm" to "Дополнительные JVM-параметры",
            "jvm_h" to "Неверные аргументы могут помешать запуску. Память -Xmx отсюда не берётся.",
            "leader" to "Режим «весь интернет на себя»",
            "leader_h" to "Лаунчер качает в несколько потоков и повторяет обрыв.",
            "gameopt" to "Игровые параметры", "gameopt_h" to "Экран и дополнительные флаги запуска.",
            "res" to "Разрешение", "fps_cap" to "Лимит FPS, 0 — без ограничения",
            "fullscreen" to "Полный экран", "nofull" to "Отключить полноэкранную оптимизацию",
            "hipri" to "Высокий приоритет процесса", "nort" to "Отключить оптимизацию в реальном времени",
            "modsup" to "Автообновление модов",
            "modsup_h" to "Если в архиве модов версия новее установленной, кнопка запуска предложит обновить моды.",
            "verify" to "Проверка сборки",
            "verify_h" to "Проверять целостность файлов модов. Если выключить, ошибка из-за расхождения файлов не появится.",
            "modmgr" to "Управление модами",
            "modmgr_h" to "Открыть папку модов текущей версии и положить туда свои файлы.",
            "open_mods" to "Открыть управление модами",
            "sources" to "Источники модов",
            "sources_h" to "Сборка Common World скачивается одним архивом modsCWL.zip.",
            "edit" to "Редактировать",
            "backups" to "Резервные копии",
            "backups_h" to "Перед установкой новых модов предыдущие файлы сохраняются.",
            "copies" to "Количество копий",
            "bg" to "Фон",
            "bg_h" to "Картинка главного меню. Новая включается, когда её выбирают.",
            "pick_bg" to "Выбрать фон",
            "look_theme" to "Тема", "look_theme_h" to "Цветовая схема интерфейса.",
            "theme" to "Тема лаунчера", "theme_hint" to "Цветовая схема. Сейчас тёмная синяя.",
            "color" to "Цвет", "blue" to "Синяя",
            "dim" to "Затемнение фона",
            "dim_hint" to "Только окна кроме главного меню. Ноль — картинка совсем без затемнения.",
            "blur_h" to "Только те же окна. Выключите — фон будет таким же чётким, как в главном меню.",
            "bg_main" to "Основной фон",
            "add_bg" to "Добавить фон",
            "effects" to "Эффекты", "effects_h" to "Какие украшения интерфейса запоминать.",
            "blur" to "Размытие фона", "anim" to "Анимации", "fade" to "Плавные переходы",
            "uistyle" to "Стиль элементов",
            "uistyle_h" to "Плотность подписей в этом окне не меняет кнопки главного меню.",
            "style_std" to "Стандартный", "style_compact" to "Компактный",
            "autostart" to "Автозапуск",
            "autostart_h" to "Запускать CWLauncher при включении телефона.",
            "autoupdate" to "Автообновление лаунчера",
            "autoupdate_h" to "Лаунчер будет проверять обновление при запуске.",
            "check_updates" to "Проверять обновления",
            "behavior" to "Поведение при запуске",
            "behavior_h" to "После запуска Minecraft лаунчер остаётся открытым.",
            "on_launch" to "Что делать при запуске", "menu_behavior" to "Показывать главное меню",
            "notes" to "Уведомления",
            "notes_h" to "Показывать уведомления о важных событиях: обновления и ошибки.",
            "time_show" to "Показ времени",
            "every_day" to "Каждый день", "every_start" to "При запуске", "every_manual" to "Вручную",
            "time_sec" to "Секунды", "time_min" to "Минуты", "time_hour" to "Часы",
            "time_day" to "Дни", "time_week" to "Недели",
            "limit_name" to "Ограничение скорости интернета", "mbit" to "Мбит/с", "band_none" to "Без ограничений",
            "cache" to "Кэш", "cache_h" to "Очистка временных файлов. Миры, аккаунты и настройки не трогаются.",
            "cache_size" to "Размер: ", "clear" to "Очистить кэш",
            "logs_h" to "Просмотр логов лаунчера и игры.",
            "extra_opts" to "Дополнительные параметры", "extra_h" to "Мелкие переключатели лаунчера.",
            "fps" to "Показать FPS", "disk" to "Проверять свободное место на диске",
            "proxy" to "Использовать системный прокси", "offline" to "Разрешить запуск без интернета",
            "dev" to "Режим разработчика", "verbose" to "Подробные логи",
            "downloads" to "Загрузки", "downloads_h" to "Папка, куда лаунчер складывает временные загрузки.",
            "open_dl" to "Открыть папку загрузок",
            "diag" to "Диагностика", "diag_h" to "Файл для поддержки: без токенов и паролей.",
            "reset_card" to "Сброс настроек",
            "reset_h" to "Вернуть поля этой формы к обычным значениям. Игру и аккаунты это не удаляет.",
            "reset_short" to "Сбросить", "wipe_ver" to "Удалить версии игры", "wipe_all" to "Удалить лаунчер",
            "wipe_re" to "Переустановка", "del_bg" to "Удалить",
            "prof_title" to "Профиль", "prof_current" to "Текущий аккаунт", "prof_none" to "Аккаунтов нет",
            "prof_none_h" to "Создайте профиль, чтобы устанавливать версии и запускать игру.",
            "prof_off" to "Оффлайн", "prof_ely" to "Аккаунт Ely.by", "prof_rename" to "Изменить имя",
            "prof_active" to "Активный", "prof_info" to "Информация об аккаунте",
            "prof_id" to "ID аккаунта", "prof_platform" to "Платформа", "prof_created" to "Дата создания",
            "prof_status" to "Статус", "prof_settings" to "Настройки аккаунта",
            "prof_avatar" to "Сменить аватарку",
            "prof_avatar_h" to "Голова скина этого аккаунта. Если файла нет, остаётся значок профиля.",
            "prof_manage" to "Управление аккаунтами", "prof_create" to "Создать новый аккаунт",
            "prof_create_h" to "Добавьте аккаунт Ely.by или оффлайн-ник.",
            "prof_ely_btn" to "Войти через Ely.by",
            "prof_ely_h" to "Войдите через Ely.by. Пароль вводится только на сайте, лаунчер его не видит.",
            "prof_list" to "Список аккаунтов", "prof_empty_list" to "Список пуст",
            "prof_back" to "Назад", "prof_offline_btn" to "Создать оффлайн"
        ))
        put("en", mapOf(
            "news" to "News", "latest" to "Latest updates", "more" to "Details →",
            "settings" to "Settings", "version" to "Choose version", "support" to "Support",
            "folder" to "Minecraft\nfolder", "mods" to "Mods", "skin" to "Skin", "logs" to "Logs",
            "close" to "Close", "close_game" to "Close", "cancel" to "Cancel",
            "launch" to "Play", "install" to "Install", "update_btn" to "Update",
            "check" to "Check build", "retry" to "Retry", "checking" to "Checking…", "starting" to "Starting",
            "running" to "Running", "go" to "Launch", "ready" to "Ready to play",
            "offline_go" to "Play offline", "java_missing" to "Java for launch was not found",
            "status_build" to "Build status", "status_err" to "Build problems",
            "status_work" to "Installation", "status_info" to "Information",
            "mods_fresh" to "Mods: up to date", "mods_check" to "Mods: check",
            "foot_none" to "Server: no data", "repeat" to "Retry",
            "news_down" to "News unavailable", "news_empty" to "The source did not respond.",
            "updates_title" to "Common World updates", "updates_empty" to "The update list is empty",
            "updates_hint" to "Press Retry to ask for the list again.",
            "saved" to "Settings saved",
            "tab_main" to "General", "tab_game" to "Game", "tab_mods" to "Mods",
            "tab_look" to "Appearance", "tab_extra" to "Advanced",
            "save" to "Save changes", "reset" to "Reset settings",
            "lang" to "Interface language",
            "lang_hint" to "Language of the launcher and Minecraft. It switches as soon as you save.",
            "lang_pick" to "Choose language", "lang_sys" to "Match the system",
            "ram" to "Memory", "ram_hint" to "The slider goes up to all the RAM in this phone.",
            "ram_of" to "of", "gb" to "GB",
            "java" to "Java", "java_h" to "Your own Java instead of the built-in one. Java 17 is required.",
            "jvm" to "Extra JVM arguments",
            "jvm_h" to "Bad arguments can stop the game from starting. -Xmx here is ignored.",
            "leader" to "Use the whole connection",
            "leader_h" to "The launcher downloads in several threads and retries drops.",
            "gameopt" to "Game options", "gameopt_h" to "Screen and extra launch flags.",
            "res" to "Resolution", "fps_cap" to "FPS limit, 0 means unlimited",
            "fullscreen" to "Fullscreen", "nofull" to "Disable fullscreen optimization",
            "hipri" to "High process priority", "nort" to "Disable real-time optimization",
            "modsup" to "Mod auto-update",
            "modsup_h" to "If the mods archive is newer, the launch button offers to update the mods.",
            "verify" to "Verify the build",
            "verify_h" to "Check mod files. Turn this off to skip the mismatch error.",
            "modmgr" to "Manage mods",
            "modmgr_h" to "Open this version's mods folder and put your own files there.",
            "open_mods" to "Open the mods folder",
            "sources" to "Mod sources",
            "sources_h" to "The Common World pack is downloaded as one modsCWL.zip archive.",
            "edit" to "Edit",
            "backups" to "Backups",
            "backups_h" to "Previous mod files are kept before a new install.",
            "copies" to "Number of copies",
            "bg" to "Background",
            "bg_h" to "Main menu picture. A new image is applied when you pick it.",
            "pick_bg" to "Choose background",
            "look_theme" to "Theme", "look_theme_h" to "Interface color scheme.",
            "theme" to "Launcher theme", "theme_hint" to "Color scheme. It stays dark blue.",
            "color" to "Color", "blue" to "Blue",
            "dim" to "Background dim",
            "dim_hint" to "Every window except the main menu. Zero means no darkening at all.",
            "blur_h" to "The same windows. Turn it off and the picture stays as sharp as the main menu.",
            "bg_main" to "Default background",
            "add_bg" to "Add background",
            "effects" to "Effects", "effects_h" to "Which interface extras to keep.",
            "blur" to "Blur the background", "anim" to "Animations", "fade" to "Smooth transitions",
            "uistyle" to "Element style",
            "uistyle_h" to "Spacing in this window does not change the main menu buttons.",
            "style_std" to "Standard", "style_compact" to "Compact",
            "autostart" to "Start with the phone",
            "autostart_h" to "Start CWLauncher when the phone turns on.",
            "autoupdate" to "Launcher auto-update",
            "autoupdate_h" to "The launcher checks for an update when it starts.",
            "check_updates" to "Check for updates",
            "behavior" to "Launch behavior",
            "behavior_h" to "The launcher stays open after Minecraft starts.",
            "on_launch" to "What to do on launch", "menu_behavior" to "Show the main menu",
            "notes" to "Notifications",
            "notes_h" to "Show notifications about updates and errors.",
            "time_show" to "Time display",
            "every_day" to "Every day", "every_start" to "On startup", "every_manual" to "Manual",
            "time_sec" to "Seconds", "time_min" to "Minutes", "time_hour" to "Hours",
            "time_day" to "Days", "time_week" to "Weeks",
            "limit_name" to "Limit download speed", "mbit" to "Mbit/s", "band_none" to "Unlimited",
            "cache" to "Cache", "cache_h" to "Clears temporary files. Worlds, accounts and settings stay.",
            "cache_size" to "Size: ", "clear" to "Clear cache",
            "logs_h" to "Launcher and game logs.",
            "extra_opts" to "Extra options", "extra_h" to "Small launcher switches.",
            "fps" to "Show FPS", "disk" to "Check free disk space",
            "proxy" to "Use the system proxy", "offline" to "Allow launch without internet",
            "dev" to "Developer mode", "verbose" to "Verbose logs",
            "downloads" to "Downloads", "downloads_h" to "Folder where the launcher keeps temporary downloads.",
            "open_dl" to "Open the downloads folder",
            "diag" to "Diagnostics", "diag_h" to "A support file without tokens or passwords.",
            "reset_card" to "Reset settings",
            "reset_h" to "Restore this form. The game and accounts are not deleted.",
            "reset_short" to "Reset", "wipe_ver" to "Delete game versions", "wipe_all" to "Uninstall launcher",
            "wipe_re" to "Reinstall", "del_bg" to "Delete",
            "prof_title" to "Profile", "prof_current" to "Current account", "prof_none" to "No accounts",
            "prof_none_h" to "Create a profile before installing a version or playing.",
            "prof_off" to "Offline", "prof_ely" to "Ely.by account", "prof_rename" to "Change name",
            "prof_active" to "Active", "prof_info" to "Account information",
            "prof_id" to "Account ID", "prof_platform" to "Platform", "prof_created" to "Created",
            "prof_status" to "Status", "prof_settings" to "Account settings",
            "prof_avatar" to "Change avatar",
            "prof_avatar_h" to "The head of this account's skin. Without a file, the profile icon stays.",
            "prof_manage" to "Account management", "prof_create" to "Create a new account",
            "prof_create_h" to "Add an Ely.by account or an offline nickname.",
            "prof_ely_btn" to "Sign in with Ely.by",
            "prof_ely_h" to "Sign in on Ely.by. The password stays on their site.",
            "prof_list" to "Account list", "prof_empty_list" to "The list is empty",
            "prof_back" to "Back", "prof_offline_btn" to "Create offline"
        ))
    }

    fun use(minecraftCode: String?) {
        var c = minecraftCode?.trim()?.lowercase(Locale.ROOT).orEmpty()
        if (c.isBlank()) c = systemCode()
        if (c.startsWith("zh")) c = if (c.contains("tw") || c.contains("hk")) "zh_tw" else "zh_cn"
        else if (c.startsWith("pt")) c = if (c.endsWith("_pt")) "pt_pt" else "pt_br"
        else if (!all.containsKey(c)) {
            val two = if (c.contains('_')) c.substringBefore('_') else c.take(2)
            c = if (all.containsKey(two)) two else if (two == "ru" || two == "be" || two == "uk" || two == "kk") "ru" else "en"
        }
        if (!all.containsKey(c)) c = "en"
        code = c
    }

    fun russian(): Boolean = code.startsWith("ru")

    fun t(key: String): String {
        all[code]?.get(key)?.let { return it }
        all["en"]?.get(key)?.let { return it }
        all["ru"]?.get(key)?.let { return it }
        return key
    }

    private fun systemCode(): String {
        val language = Locale.getDefault().language.lowercase(Locale.ROOT)
        return if (language == "ru" || language == "be" || language == "uk" || language == "kk") "ru" else "en"
    }

    private fun put(lang: String, map: Map<String, String>) {
        all[lang] = map
    }
}
